SHOW DATABASES;
CREATE DATABASE SIS_RESERVACIONES;
USE SIS_RESERVACIONES;

CREATE TABLE PELICULAS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL UNIQUE,
DUR_MIN INT NOT NULL
);

CREATE TABLE CLIENTES (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45),
APELLIDO VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE SALAS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
N_ASIENTOS INT NOT NULL
);

CREATE TABLE FUNCIONES (
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_PELICULA INT NOT NULL,
ID_SALA INT NOT NULL,
HORA_INICIO DATETIME NOT NULL,
FOREIGN KEY (ID_PELICULA) REFERENCES PELICULAS(ID),
FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID)
);

CREATE TABLE ASIENTOS (
ID INT PRIMARY KEY AUTO_INCREMENT,
FILA CHAR(1) NOT NULL,
NUMERO INT NOT NULL,
ID_SALA INT NOT NULL,
FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID)
);

CREATE TABLE RESERVACIONES (
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_FUNCION INT NOT NULL,
ID_CLIENTE INT NOT NULL, 
FOREIGN KEY (ID_FUNCION) REFERENCES FUNCIONES(ID),
FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(ID)
);

CREATE TABLE (
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_RESERVACION INT NOT NULL,
ID_ASIENTO INT NOT NULL,
FOREIGN KEY (ID_RESERVACION) REFERENCES RESERVACIONES(ID),
FOREIGN KEY (ID_ASIENTO) REFERENCES ASIENTOS(ID)
);

INSERT INTO PELICULAS (NOMBRE, DUR_MIN)
VALUES ('Blade Runner 2049', 153),
('Blade Runner', 127);

INSERT INTO CLIENTES (NOMBRE, APELLIDO, EMAIL)
VALUES ('David', 'May', 'dmay@gmail.com'), ('Theresa', 'Davis', 'tdavis@gmail.com');

INSERT INTO SALAS (NOMBRE, N_ASIENTOS)
VALUES ('SALA 1', 45), ('SALA 2', 30);

INSERT INTO FUNCIONES (ID_PELICULA, ID_SALA, HORA_INICIO)
VALUES (1, 2, 2021-01-01 12:45:00), (2, 1, 2021-01-01 12:30:00)

INSERT INTO ASIENTOS (FILA, NUMERO, ID_SALA)
VALUES (1, 1, 1), (1, 2, 1), (1, 1, 2), (1, 2, 2)

SHOW TABLES;

SELECT * FROM ASIENTOS; # REEMPLAZAR ASIENTOS POR PELICULAS, CLIENTES, SALAS O FUNCIONES
